### PR TITLE
fix(purchase): update `AutoRenewingPlan` to support optional values

### LINKED ISSUE #257: [purchase] Instantiation of AutoRenewingPlan object fails
### Affected Versions

1.11.0

### Description

Got the error message during deserialization:
Cannot create an instance of "Imdhemy\GooglePlay\Domain\Purchase\Subscription\AutoRenewingPlan" from serialized data because its constructor requires the following parameters to be present : `installmentDetails`, `priceChangeDetails` etc. Also the `autoRenewEnabled` parameter is not given if the subscription is cancelled.

### How to reproduce

The returned data of the purchases.subscriptionsv2.get API will look like:
```json
{
  "kind": "androidpublisher#subscriptionPurchaseV2",
  "startTime": "2025-10-24T11:03:42.097Z",
  "regionCode": "DE",
  "subscriptionState": "SUBSCRIPTION_STATE_ACTIVE",
  "latestOrderId": "GPA.xxxx-xxxx-xxxx-xxxx",
  "testPurchase": {},
  "acknowledgementState": "ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED",
  "externalAccountIdentifiers": {
    "obfuscatedExternalAccountId": "VioUT4kHwh0ur8crMexs"
  },
  "lineItems": [
    {
      "productId": "subscription.test",
      "expiryTime": "2025-10-24T11:06:41.541Z",
      "autoRenewingPlan": {
        "autoRenewEnabled": true,
        "recurringPrice": {
          "currencyCode": "EUR",
          "units": "4",
          "nanos": 190000000
        }
      },
      "offerDetails": {
        "basePlanId": "test-one-month",
        "offerId": "test-one-month-trial"
      },
      "latestSuccessfulOrderId": "GPA.xxxx-xxxx-xxxx-xxxx"
    }
  ]
}
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BernhardtD**
| Q             | A                                                        |
|---------------|----------------------------------------------------------|
| Tickets       | Fix #257 |
| License       | MIT                                                      |

### Updated
- updated constructor of [Domain\Purchase\Subscription\AutoRenewingPlan](https://github.com/imdhemy/google-play-billing/blob/1.x/src/Domain/Purchase/Subscription/AutoRenewingPlan.php)
- added test case

Closes #257

### CODE REVIEW

File: src/Domain/Purchase/Subscription/AutoRenewingPlan.php [hunk 1]
```diff
@@ -14,10 +14,10 @@
 final readonly class AutoRenewingPlan
 {
     public function __construct(
-        public bool $autoRenewEnabled,
         public Money $recurringPrice,
-        public SubscriptionItemPriceChangeDetails $priceChangeDetails,
-        public InstallmentPlan $installmentDetails,
+        public ?bool $autoRenewEnabled = false,
```
Comment (imdhemy) [inline src/Domain/Purchase/Subscription/AutoRenewingPlan.php]: `null` should be used as the default value. The semantic meaning of `null` is the absence of value, distinguishing it from either having a value of `true` of `false`.

File: tests/Domain/Purchase/Subscription/AutoRenewingPlanTest.php [hunk 2]
```diff
@@ -48,4 +48,23 @@ public function instantiate(): void
...
+    {
+        $data = [
+            'recurringPrice' => [
+                'currencyCode' => $this->faker->currencyCode(),
+                'units' => (string)$this->faker->randomNumber(5),
+                'nanos' => $this->faker->randomNumber(5),
+            ],
+        ];
+
+        $actual = $this->normalizer->normalize($data, AutoRenewingPlan::class);
```
Comment (imdhemy) [inline tests/Domain/Purchase/Subscription/AutoRenewingPlanTest.php:63]: [nitpick] Please add an empty line after the `Act` step to distinguish it from the following `Assert` section. [[AAA](https://github.com/openkairos/documentation/blob/main/docs/technical/unit-testing.md)]

**Review by imdhemy — CHANGES_REQUESTED** [review]

**Review by imdhemy — APPROVED** [review]
@BernhardtD Thank you!
