### PR TITLE
fix(purchase): instantiate `ExternalAccountIdentifiers` with optional fields

### LINKED ISSUE #228: instantiation of ExternalAccountIdentifiers fails
### Affected Versions

1.10.0

### Description

Got the error message during deserialization:
Cannot create an instance of "Imdhemy\GooglePlay\Domain\Purchase\Subscription\ExternalAccountIdentifiers" from serialized data because its constructor requires the following parameters to be present : "$externalAccountId", "$obfuscatedExternalProfileId".

### How to reproduce

We created a test subscription and set the [setObfuscatedProfileId](https://developer.android.com/reference/com/android/billingclient/api/BillingFlowParams.Builder#setObfuscatedProfileId(java.lang.String)) to the value `VioUT4kHwh0ur8crMexs` within our application.
The returned data of the purchases.subscriptionsv2.get API will look like:
```json
{
  "kind": "androidpublisher#subscriptionPurchaseV2",
  "startTime": "2025-10-24T11:03:42.097Z",
  "regionCode": "DE",
  "subscriptionState": "SUBSCRIPTION_STATE_ACTIVE",
  "latestOrderId": "GPA.xxxx-xxxx-xxxx-xxxx",
  "testPurchase": {},
  "acknowledgementState": "ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED",
  "externalAccountIdentifiers": {
    "obfuscatedExternalAccountId": "VioUT4kHwh0ur8crMexs"
  },
  "lineItems": [
    {
      "productId": "subscription.test",
      "expiryTime": "2025-10-24T11:06:41.541Z",
      "autoRenewingPlan": {
        "autoRenewEnabled": true,
        "recurringPrice": {
          "currencyCode": "EUR",
          "units": "4",
          "nanos": 190000000
        }
      },
      "offerDetails": {
        "basePlanId": "test-one-month",
        "offerId": "test-one-month-trial"
      },
      "latestSuccessfulOrderId": "GPA.xxxx-xxxx-xxxx-xxxx"
    }
  ]
}
```

Only the `obfuscatedExternalAccountId` parameter is set in the `externalAccountIdentifiers` object. The documentation of the object [externalaccountidentifiers](https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2#externalaccountidentifiers) specifies the `externalAccountId` and the `obfuscatedExternalProfileId` as optional.

### Possible Solution

Update the constructor of the class [Imdhemy\GooglePlay\Domain\Purchase\Subscription\ExternalAccountIdentifiers](https://github.com/imdhemy/google-play-billing/blob/1.x/src/Domain/Purchase/Subscription/ExternalAccountIdentifiers.php):

```php
final readonly class ExternalAccountIdentifiers
{
    public function __construct(
        public ?string $externalAccountId,
        public string $obfuscatedExternalAccountId,
        public ?string $obfuscatedExternalProfileId,
    ) {
    }
}
```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by BernhardtD**
| Q             | A                                                        |
|---------------|----------------------------------------------------------|
| Tickets       | Fix #228  |
| License       | MIT                                                      |

### Updated
- updated constructor of [Domain\Purchase\Subscription\ExternalAccountIdentifiers](https://github.com/imdhemy/google-play-billing/blob/1.x/src/Domain/Purchase/Subscription/ExternalAccountIdentifiers.php) to create instance if `externalAccountId`  and the `obfuscatedExternalProfileId` are not set
- added test case

Closes #228

### CODE REVIEW

File: tests/Domain/Purchase/SubscriptionServiceTest.php [hunk 1]
```diff
@@ -40,6 +40,38 @@ public function get_subscription(): void
         );
     }
 
+    /** @test */
+    public function get_subscription_without_external_account_id(): void
```
Comment (imdhemy) [inline tests/Domain/Purchase/SubscriptionServiceTest.php]: This tests is not needed. You just need to add a new test-case to this file.

https://github.com/imdhemy/google-play-billing/blob/0ad81cf2fb1095bf40358a3d0f2dace5d0a25b10/tests/Domain/Purchase/Subscription/ExternalAccountIdentifiersTest.php#L10

**Review by imdhemy — CHANGES_REQUESTED** [review]
Thanks a bunch! Could you please address my comment?

File: tests/Domain/Purchase/SubscriptionServiceTest.php (hunk 1 above)
Comment (BernhardtD) [reply tests/Domain/Purchase/SubscriptionServiceTest.php]: Thank you for pointing that out. I removed the tests and added a new one to the `ExternalAccountIdentifiersTest.php` file.

**Review by imdhemy — APPROVED** [review]
@BernhardtD Thank you!
